### ISSUE TITLE
catkin_make fails, unable to find ric_interface_ros

### ISSUE THREAD

**Issue by fauzanzaid** [robotican/lizi#1]
Hello, I am unable to build the current package. On running `catkin_make`, I get an error stating the following:

    CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
      Could not find a package configuration file provided by "ric_interface_ros"
      with any of the following names:
    
        ric_interface_rosConfig.cmake
        ric_interface_ros-config.cmake
    
      Add the installation prefix of "ric_interface_ros" to CMAKE_PREFIX_PATH or
      set "ric_interface_ros_DIR" to a directory containing one of the above
      files.  If "ric_interface_ros" provides a separate development package or
      SDK, be sure it has been installed.
    Call Stack (most recent call first):
      lizi/lizi_hw/CMakeLists.txt:10 (find_package)

It seems to me that this package is in active development. The [repository link](https://github.com/robotican/lizi_robot) for the package referenced in the [ROS Wiki](http://wiki.ros.org/lizi) for the lizi robot is dead. Could you tell me from where can I download the old lizi robot package for which the documentation is available on ROS Wiki, or how to resolve the error in the new package?

**Comment by elhayra** [comment]
Hi fauzanaid,

As you figured, this package is under development. The old Lizi package is deprecated.

In case you need help with the old Lizi package, please write to:
support@robotican.net
Specify the Lizi ID and customer name.

If you just need a simulation of the Lizi robot, I suggest you wait until we finish the development of this package (about a month)
